const CONSTANTS = {
  GOLD_TYPES: {
    SGB: "SGB",
    PHYSICAL_GOLD: "PHYSICAL_GOLD",
    MF_OR_ETF: "MF_OR_ETF",
  },
  DEBT_TYPES: {
    SAVING_ACCOUNT_BALANCE: "SAVING_ACCOUNT_BALANCE",
    BONDS: "BONDS",
    GOVERNMENT_SECURITIES: "GOVERNMENT_SECURITIES",
    FD: "FD",
    DEBT_MF: "DEBT_MF",
  },
  INDIAN_STOCK_TYPES: {
    LARGE_CAP: "LARGE_CAP",
    MID_CAP: "MID_CAP",
    SMALL_CAP: "SMALL_CAP",
  },
  REGULAR_EXPRESSIONS: {
    PHONE_NUMBER: /^((\+91?)|\+)?[7-9][0-9]{9}$/,
  },
};

module.exports = CONSTANTS;
