const CONSTANTS = require("./constants");

const generateOTP = () => {
  return (
    Math.floor(Math.random() * (999999 - 100000 + 1)) + 100000
  ).toString();
};

const errorHandler = (errorMsg) => {
  return {
    msg: errorMsg,
  };
};

const UserAdminJSOptions = {
  sort: {
    sortBy: CONSTANTS.MODEL_PROPERTIES.ID,
  },
  listProperties: [
    CONSTANTS.MODEL_PROPERTIES.NAME,
    CONSTANTS.MODEL_PROPERTIES.EMAIL,
    CONSTANTS.MODEL_PROPERTIES.MOBILE_NUMBER,
    CONSTANTS.MODEL_PROPERTIES.DATE_OF_BIRTH,
  ],
  filterProperties: [
    CONSTANTS.MODEL_PROPERTIES.NAME,
    CONSTANTS.MODEL_PROPERTIES.EMAIL,
    CONSTANTS.MODEL_PROPERTIES.MOBILE_NUMBER,
  ],
  editProperties: [
    CONSTANTS.MODEL_PROPERTIES.NAME,
    CONSTANTS.MODEL_PROPERTIES.EMAIL,
    CONSTANTS.MODEL_PROPERTIES.MOBILE_NUMBER,
    CONSTANTS.MODEL_PROPERTIES.DATE_OF_BIRTH,
  ],
  showProperties: [
    CONSTANTS.MODEL_PROPERTIES.ID,
    CONSTANTS.MODEL_PROPERTIES.NAME,
    CONSTANTS.MODEL_PROPERTIES.EMAIL,
    CONSTANTS.MODEL_PROPERTIES.MOBILE_NUMBER,
    CONSTANTS.MODEL_PROPERTIES.DATE_OF_BIRTH,
    CONSTANTS.MODEL_PROPERTIES.CREATED_AT,
    CONSTANTS.MODEL_PROPERTIES.UPDATED_AT,
  ],
};

const IndianStockAdminJSOptions = {
  listProperties: [
    CONSTANTS.MODEL_PROPERTIES.TITLE,
    CONSTANTS.MODEL_PROPERTIES.QUANTITY,
    CONSTANTS.MODEL_PROPERTIES.PRICE,
    CONSTANTS.MODEL_PROPERTIES.VALUE,
    CONSTANTS.MODEL_PROPERTIES.TYPE,
  ],
  filterProperties: [
    CONSTANTS.MODEL_PROPERTIES.TYPE,
    CONSTANTS.MODEL_PROPERTIES.USER_ID,
  ],
  editProperties: [
    CONSTANTS.MODEL_PROPERTIES.TITLE,
    CONSTANTS.MODEL_PROPERTIES.QUANTITY,
    CONSTANTS.MODEL_PROPERTIES.PRICE,
    CONSTANTS.MODEL_PROPERTIES.TYPE,
    CONSTANTS.MODEL_PROPERTIES.USER_ID,
  ],
  showProperties: [
    CONSTANTS.MODEL_PROPERTIES.ID,
    CONSTANTS.MODEL_PROPERTIES.TITLE,
    CONSTANTS.MODEL_PROPERTIES.QUANTITY,
    CONSTANTS.MODEL_PROPERTIES.PRICE,
    CONSTANTS.MODEL_PROPERTIES.VALUE,
    CONSTANTS.MODEL_PROPERTIES.TYPE,
    CONSTANTS.MODEL_PROPERTIES.USER_ID,
    CONSTANTS.MODEL_PROPERTIES.CREATED_AT,
    CONSTANTS.MODEL_PROPERTIES.UPDATED_AT,
  ],
};

const MutualFundAdminJSOptions = {
  listProperties: [
    CONSTANTS.MODEL_PROPERTIES.TITLE,
    CONSTANTS.MODEL_PROPERTIES.QUANTITY,
    CONSTANTS.MODEL_PROPERTIES.NAV,
    CONSTANTS.MODEL_PROPERTIES.VALUE,
  ],
  filterProperties: [CONSTANTS.MODEL_PROPERTIES.USER_ID],
  editProperties: [
    CONSTANTS.MODEL_PROPERTIES.TITLE,
    CONSTANTS.MODEL_PROPERTIES.QUANTITY,
    CONSTANTS.MODEL_PROPERTIES.NAV,
    CONSTANTS.MODEL_PROPERTIES.SMALL_CAP_PERCENTAGE,
    CONSTANTS.MODEL_PROPERTIES.MID_CAP_PERCENTAGE,
    CONSTANTS.MODEL_PROPERTIES.LARGE_CAP_PERCENTAGE,
    CONSTANTS.MODEL_PROPERTIES.CASH_PERCENTAGE,
    CONSTANTS.MODEL_PROPERTIES.USER_ID,
  ],
  showProperties: [
    CONSTANTS.MODEL_PROPERTIES.ID,
    CONSTANTS.MODEL_PROPERTIES.TITLE,
    CONSTANTS.MODEL_PROPERTIES.QUANTITY,
    CONSTANTS.MODEL_PROPERTIES.NAV,
    CONSTANTS.MODEL_PROPERTIES.VALUE,
    CONSTANTS.MODEL_PROPERTIES.SMALL_CAP_PERCENTAGE,
    CONSTANTS.MODEL_PROPERTIES.MID_CAP_PERCENTAGE,
    CONSTANTS.MODEL_PROPERTIES.LARGE_CAP_PERCENTAGE,
    CONSTANTS.MODEL_PROPERTIES.CASH_PERCENTAGE,
    CONSTANTS.MODEL_PROPERTIES.USER_ID,
    CONSTANTS.MODEL_PROPERTIES.CREATED_AT,
    CONSTANTS.MODEL_PROPERTIES.UPDATED_AT,
  ],
};

const DebtAdminJSOptions = {
  sort: {
    sortBy: CONSTANTS.MODEL_PROPERTIES.VALUE,
    direction: CONSTANTS.MODEL_PROPERTIES.DESC,
  },
  listProperties: [
    CONSTANTS.MODEL_PROPERTIES.TITLE,
    CONSTANTS.MODEL_PROPERTIES.VALUE,
    CONSTANTS.MODEL_PROPERTIES.TYPE,
  ],
  filterProperties: [
    CONSTANTS.MODEL_PROPERTIES.TYPE,
    CONSTANTS.MODEL_PROPERTIES.USER_ID,
  ],
  editProperties: [
    CONSTANTS.MODEL_PROPERTIES.TITLE,
    CONSTANTS.MODEL_PROPERTIES.VALUE,
    CONSTANTS.MODEL_PROPERTIES.TYPE,
    CONSTANTS.MODEL_PROPERTIES.USER_ID,
  ],
  showProperties: [
    CONSTANTS.MODEL_PROPERTIES.ID,
    CONSTANTS.MODEL_PROPERTIES.TITLE,
    CONSTANTS.MODEL_PROPERTIES.VALUE,
    CONSTANTS.MODEL_PROPERTIES.TYPE,
    CONSTANTS.MODEL_PROPERTIES.USER_ID,
    CONSTANTS.MODEL_PROPERTIES.CREATED_AT,
    CONSTANTS.MODEL_PROPERTIES.UPDATED_AT,
  ],
};

const GoldAdminJSOptions = {
  sort: {
    sortBy: CONSTANTS.MODEL_PROPERTIES.VALUE,
    direction: CONSTANTS.MODEL_PROPERTIES.DESC,
  },
  listProperties: [
    CONSTANTS.MODEL_PROPERTIES.TITLE,
    CONSTANTS.MODEL_PROPERTIES.VALUE,
    CONSTANTS.MODEL_PROPERTIES.TYPE,
  ],
  filterProperties: [
    CONSTANTS.MODEL_PROPERTIES.TYPE,
    CONSTANTS.MODEL_PROPERTIES.USER_ID,
  ],
  editProperties: [
    CONSTANTS.MODEL_PROPERTIES.TITLE,
    CONSTANTS.MODEL_PROPERTIES.VALUE,
    CONSTANTS.MODEL_PROPERTIES.TYPE,
    CONSTANTS.MODEL_PROPERTIES.USER_ID,
  ],
  showProperties: [
    CONSTANTS.MODEL_PROPERTIES.ID,
    CONSTANTS.MODEL_PROPERTIES.TITLE,
    CONSTANTS.MODEL_PROPERTIES.VALUE,
    CONSTANTS.MODEL_PROPERTIES.TYPE,
    CONSTANTS.MODEL_PROPERTIES.USER_ID,
    CONSTANTS.MODEL_PROPERTIES.CREATED_AT,
    CONSTANTS.MODEL_PROPERTIES.UPDATED_AT,
  ],
};

const CryptoAdminJSOptions = {
  sort: {
    sortBy: CONSTANTS.MODEL_PROPERTIES.VALUE,
    direction: CONSTANTS.MODEL_PROPERTIES.DESC,
  },
  listProperties: [
    CONSTANTS.MODEL_PROPERTIES.TITLE,
    CONSTANTS.MODEL_PROPERTIES.VALUE,
  ],
  filterProperties: [CONSTANTS.MODEL_PROPERTIES.USER_ID],
  showProperties: [
    CONSTANTS.MODEL_PROPERTIES.ID,
    CONSTANTS.MODEL_PROPERTIES.TITLE,
    CONSTANTS.MODEL_PROPERTIES.VALUE,
    CONSTANTS.MODEL_PROPERTIES.USER_ID,
    CONSTANTS.MODEL_PROPERTIES.CREATED_AT,
    CONSTANTS.MODEL_PROPERTIES.UPDATED_AT,
  ],
};

const LiabiltyAdminJSOptions = {
  sort: {
    sortBy: CONSTANTS.MODEL_PROPERTIES.VALUE,
    direction: CONSTANTS.MODEL_PROPERTIES.DESC,
  },
  listProperties: [
    CONSTANTS.MODEL_PROPERTIES.TITLE,
    CONSTANTS.MODEL_PROPERTIES.VALUE,
  ],
  filterProperties: [CONSTANTS.MODEL_PROPERTIES.USER_ID],
  showProperties: [
    CONSTANTS.MODEL_PROPERTIES.ID,
    CONSTANTS.MODEL_PROPERTIES.TITLE,
    CONSTANTS.MODEL_PROPERTIES.VALUE,
    CONSTANTS.MODEL_PROPERTIES.USER_ID,
    CONSTANTS.MODEL_PROPERTIES.CREATED_AT,
    CONSTANTS.MODEL_PROPERTIES.UPDATED_AT,
  ],
};

module.exports = {
  generateOTP,
  errorHandler,
  UserAdminJSOptions,
  IndianStockAdminJSOptions,
  MutualFundAdminJSOptions,
  DebtAdminJSOptions,
  GoldAdminJSOptions,
  CryptoAdminJSOptions,
  LiabiltyAdminJSOptions,
};
